/// A Dart implementation of TSID (Time-Sorted Unique Identifier).
///
/// TSIDs are k-sortable, 64-bit identifiers designed to be generated by distributed
/// systems. They are an alternative to UUIDs and offer chronological ordering.
/// This library provides a `Tsid` class and a `TsidFactory` for creating TSIDs,
/// supporting different configurations for node bits and custom epochs.
/// It is a port of the original Java TSID library.
library;

export 'src/tsid_stub.dart'
    if (dart.library.io) 'src/tsid_default.dart'
    if (dart.library.html) 'src/tsid_web.dart';
export 'src/tsid_error.dart';
